#!/bin/zsh

mod_amount=5
image="/usr/share/icons/breeze/applets/22/speaker.svg"
bgcolor=0x50505050

if [[ $1 == "up" ]]; then
    pamixer --increase $mod_amount
elif [[ $1 == "down" ]]; then
    pamixer --decrease $mod_amount
fi


rpnpid=$(pidof reentrant-progress-notificator)

if [[ $? == 1 ]]; then
    reentrant-progress-notificator \
    	--background-color=$bgcolor \
		--speaker-image-path="$image" \
    	$mod_amount $(pamixer --get-volume)
else
    if [[ $1 == "up" ]]; then
        reentrant-progress-notificator + $rpnpid
    elif [[ $1 == "down" ]]; then
        reentrant-progress-notificator - $rpnpid
   fi
fi

